# Changes here will be overwritten by Copier
_commit: 1.5.2
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2020'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC License
insiders: false
project_description: Run a command, print its output only if it fails.
project_name: failprint
python_package_command_line_name: failprint
python_package_distribution_name: failprint
python_package_import_name: failprint
repository_name: failprint
repository_namespace: pawamoy
repository_provider: github.com

